app/blueprints/admin.py
from flask import (
    current_app,
    flash,
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    abort,
    make_response,
)
from ..models import Option, Page, User, Category, Tag, Post, Comment, Link
from ..extensions import db
from ..forms import (
    LoginForm,
    PostForm,
    PageForm,
    CategoryForm,
    TagForm,
    CommentForm,
    OptionForm,
    LinkForm,
    SearchForm,
)

from flask_login import login_required, current_user

from ..utils import redirect_back

admin_bp = Blueprint("admin", __name__)


@admin_bp.before_request
@login_required
def login_protect():
    pass


@admin_bp.route("/option", methods=["GET", "POST"])
def option():
    form = OptionForm()
    blog_title = Option.query.filter_by(name="blog_title").first()
    blog_sub_title = Option.query.filter_by(name="blog_sub_title").first()
    blog_navbar = Option.query.filter_by(name="blog_navbar").first()
    blog_footer = Option.query.filter_by(name="blog_footer").first()
    sidebar_comment = Option.query.filter_by(name="sidebar_comment").first()
    comment_review = Option.query.filter_by(name="comment_review").first()

    if form.validate_on_submit():
        blog_title.value = form.blog_title.data
        blog_sub_title.value = form.blog_sub_title.data
        blog_navbar.value = form.blog_navbar.data
        blog_footer.value = form.blog_footer.data
        sidebar_comment.value = form.sidebar_comment.data
        comment_review.value = form.comment_review.data

        db.session.commit()
        flash("设置保存成功", "success")
        return redirect(url_for("main.index"))
    form.blog_title.data = blog_title.value
    form.blog_sub_title.data = blog_sub_title.value
    form.blog_navbar.data = blog_navbar.value
    form.blog_footer.data = blog_footer.value
    form.sidebar_comment.data = int(sidebar_comment.value)
    form.comment_review.data = int(comment_review.value)

    return render_template("admin/option.html", form=form)


@admin_bp.route("/manage_pages")
def manage_pages():
    pages = Page.query.all()
    return render_template("admin/manage_pages.html", pages=pages)


@admin_bp.route("/edit_page/<int:page_id>", methods=["GET", "POST"])
def edit_page(page_id):
    page = Page.query.get_or_404(page_id)
    form = PageForm()
    if form.validate_on_submit():
        page.title = form.title.data
        page.slug = form.slug.data
        page.content = form.content.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_pages"))
    form.title.data = page.title
    form.slug.data = page.slug
    form.content.data = page.content
    return render_template("admin/page.html", form=form, type="编辑")


@admin_bp.route("/add_page", methods=["GET", "POST"])
def add_page():
    form = PageForm()
    if form.validate_on_submit():
        page = Page(
            title=form.title.data, slug=form.slug.data, content=form.content.data
        )
        db.session.add(page)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_pages"))
    return render_template("admin/page.html", form=form, type="添加")


@admin_bp.route("/page/<int:page_id>/delete", methods=["POST"])
def delete_page(page_id):
    page = Page.query.get_or_404(page_id)
    db.session.delete(page)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_categories")
def manage_categories():
    categories = Category.query.all()
    return render_template("admin/manage_categories.html", categories=categories)


@admin_bp.route("/edit_category/<int:category_id>", methods=["GET", "POST"])
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_categories"))
    form.name.data = category.name
    return render_template("admin/category.html", form=form, type="编辑")


@admin_bp.route("/add_category", methods=["GET", "POST"])
def add_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_categories"))
    return render_template("admin/category.html", form=form, type="添加")


@admin_bp.route("/category/<int:category_id>/delete", methods=["POST"])
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_tags")
def manage_tags():
    tags = Tag.query.all()
    return render_template("admin/manage_tags.html", tags=tags)


@admin_bp.route("/edit_tag/<int:tag_id>", methods=["GET", "POST"])
def edit_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    form = TagForm()
    if form.validate_on_submit():
        tag.name = form.name.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_tags"))
    form.name.data = tag.name
    return render_template("admin/tag.html", form=form, type="编辑")


@admin_bp.route("/add_tag", methods=["GET", "POST"])
def add_tag():
    form = TagForm()
    if form.validate_on_submit():
        tag = Tag(name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_tags"))
    return render_template("admin/tag.html", form=form, type="添加")


@admin_bp.route("/tag/<int:tag_id>/delete", methods=["POST"])
def delete_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_posts")
def manage_posts():
    page = request.args.get("page", 1, type=int)
    pagination = Post.query.order_by(Post.created.desc()).paginate(page, per_page=10)

    return render_template(
        "admin/manage_posts.html",
        page=page,
        pagination=pagination,
        posts=pagination.items,
    )


@admin_bp.route("/write_post", methods=["GET", "POST"])
def write_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        content_html = request.form["fancy-editormd-html-code"]
        category = Category.query.get(form.category.data)
        tags = []
        for tag_id in form.tags.data:
            tag = Tag.query.get_or_404(tag_id)
            tags.append(tag)

        post = Post(
            title=title,
            content=content,
            content_html=content_html,
            category=category,
            tags=tags,
        )

        db.session.add(post)
        db.session.commit()
        flash("文章已发布", "success")
        return redirect(url_for("main.post", post_id=post.id))
    return render_template("admin/post.html", form=form, type="写")


@admin_bp.route("/edit_post/<int:post_id>", methods=["GET", "POST"])
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.content_html = request.form["fancy-editormd-html-code"]
        post.category_id = form.category.data
        tags = []
        for tag_id in form.tags.data:
            tag = Tag.query.get_or_404(tag_id)
            tags.append(tag)
        post.tags = tags
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("main.post", post_id=post_id))
    form.title.data = post.title
    form.category.data = post.category

    tag_id_list = []
    for tag in post.tags:
        tag_id_list.append(tag.id)
    form.tags.data = tag_id_list

    form.content.data = post.content

    return render_template("admin/post.html", form=form, type="编辑")


@admin_bp.route("/post/<int:post_id>/delete", methods=["POST"])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_comments")
def manage_comments():
    page = request.args.get("page", 1, type=int)

    if request.args.get("filter") == "review":
        pagination = (
            Comment.query.filter_by(reviewed=False)
            .order_by(Comment.created.desc())
            .paginate(page, per_page=10)
        )
    elif request.args.get("filter") == "admin":
        pagination = (
            Comment.query.filter_by(author="admin")
            .order_by(Comment.created.desc())
            .paginate(page, per_page=10)
        )
    else:
        pagination = Comment.query.order_by(Comment.created.desc()).paginate(
            page, per_page=10
        )

    return render_template(
        "admin/manage_comments.html",
        page=page,
        pagination=pagination,
        comments=pagination.items,
        total_count=Comment.query.count(),
        review_count=Comment.query.filter_by(reviewed=False).count(),
    )


@admin_bp.route("/comment/<int:comment_id>/approve", methods=["POST"])
def approve_comment(comment_id):
    # 切换审核状态
    comment = Comment.query.get_or_404(comment_id)

    if comment.reviewed:
        comment.reviewed = False
    else:
        comment.reviewed = True

    db.session.commit()
    flash("操作成功", "success")
    return redirect_back()


@admin_bp.route("/comment/<int:comment_id>/delete", methods=["POST"])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_links")
def manage_links():

app/blueprints/main.py
import random
from flask import (
    current_app,
    g,
    flash,
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    abort,
    make_response,
)
from ..models import Option, Page, User, Category, Tag, Post, Comment, Link
from ..forms import (
    LoginForm,
    PostForm,
    PageForm, 
    CategoryForm,
    TagForm,
    CommentForm,
    OptionForm,
    SearchForm,
    LoginCommentForm,
)
from ..extensions import db
from sqlalchemy import extract, and_, or_
from ..utils import redirect_back
from flask_login import current_user


main_bp = Blueprint("main", __name__)


@main_bp.route("/")
def index():
    pagination = Post.query.order_by(Post.created.desc()).paginate(per_page=10)
    return render_template(
        "main/index.html", posts=pagination.items, pagination=pagination
    )


@main_bp.route("/page/<string:slug>")
def page(slug):
    page = Page.query.filter(Page.slug == slug).first_or_404()
    return render_template("main/page.html", page=page,)


@main_bp.route("/user/<int:user_id>")
def user(user_id):
    user = User.query.get_or_404(user_id)
    pagination = (
        Post.query.with_parent(user)
        .order_by(Post.created.desc())
        .paginate(per_page=10)
    )
    return render_template(
        "main/archive.html",
        type="作者",
        archive=user,
        posts=pagination.items,
        pagination=pagination,
    )

@main_bp.route("/category/<int:category_id>")
def category(category_id):
    category = Category.query.get_or_404(category_id)
    pagination = (
        Post.query.with_parent(category)
        .order_by(Post.created.desc())
        .paginate(per_page=10)
    )
    return render_template(
        "main/archive.html",
        type="分类",
        archive=category,
        posts=pagination.items,
        pagination=pagination,
    )


@main_bp.route("/tag/<int:tag_id>")
def tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    pagination = (
        Post.query.with_parent(tag).order_by(Post.created.desc()).paginate(per_page=10)
    )
    return render_template(
        "main/archive.html",
        type="标签",
        archive=tag,
        posts=pagination.items,
        pagination=pagination,
    )


@main_bp.route("/archive/<int:archive_year>/<int:archive_month>")
def archive(archive_year, archive_month):

    posts = Post.query.filter(
        and_(
            extract("year", Post.created) == archive_year,
            extract("month", Post.created) == archive_month,
        )
    )
    pagination = posts.paginate(per_page=10)
    archive = {
        "name": str(archive_year) + "年" + str(archive_month) + "月",
        "posts": posts.all(),
    }
    return render_template(
        "main/archive.html",
        type="归档",
        archive=archive,
        posts=pagination.items,
        pagination=pagination,
    )


@main_bp.route("/search")
def search():
    keyword = request.args.get("keyword")
    pagination = Post.query.filter(
        or_(
            Post.content.like("%" + keyword + "%"), Post.title.like("%" + keyword + "%")
        )
    ).paginate(per_page=10)
    archive = {"name": keyword, "posts": pagination.items}
    return render_template(
        "main/archive.html",
        type="搜索",
        archive=archive,
        posts=archive["posts"],
        pagination=pagination,
    )


@main_bp.route("/post/<int:post_id>")
def post(post_id):

    if current_user.is_authenticated:
        form = LoginCommentForm()
    else:
        form = CommentForm()

    # 一篇文章
    post = Post.query.get_or_404(post_id)
    # 递增阅读次数
    post.read_count = post.read_count + 1
    db.session.commit()
    # 评论列表
    pagination = (
        Comment.query.with_parent(post)
        .filter_by(reviewed=True)
        .order_by(Comment.created.desc())
        .paginate(per_page=10)
    )

    # 获取上篇下篇
    p_index = -1
    n_index = -1
    posts = Post.query.order_by(Post.created)
    for i, p in enumerate(posts):
        if p.id == post_id:
            p_index = i - 1
            n_index = i + 1

    if n_index == posts.count():
        next_post = None
    else:
        next_post = posts[n_index]

    if p_index == -1:
        prev_post = None
    else:
        prev_post = posts[p_index]

    return render_template(
        "main/post.html",
        post=post,
        post_comments=pagination.items,
        pagination=pagination,
        form=form,
        prev_post=prev_post,
        next_post=next_post,
    )


@main_bp.route("/post/random")
def random_post():
    post = Post.query
    if not post.count():
        flash('没有找到文章','info')
        return redirect(url_for("main.index"))
    i = random.randint(0, post.count() - 1)
    return redirect(url_for("main.post", post_id=post[i].id))


@main_bp.route("/post/<int:post_id>/comment", methods=["POST"])
def comment_post(post_id):  # 评论帖子或回复帖子中的评论

    form = CommentForm()

    if form.validate_on_submit():

        comment = Comment(
            post_id=post_id,
            author=form.author.data,
            mail=form.mail.data,
            url=form.url.data,
            content=form.content.data,
            ip=request.remote_addr,
        )

        # 管理员发表的评论 或 评论审核被关闭
        if current_user.is_authenticated or not int(g.options["comment_review"]):
            comment.reviewed = True

        # 被回复的评论id
        comment_id = request.args.get("comment_id")
        if comment_id:  # 关联父评论
            comment.replied = Comment.query.get_or_404(comment_id)

            # send_new_reply_email(replied_comment)

        db.session.add(comment)
        db.session.commit()

        if int(comment.reviewed):
            flash("发表成功", "success")
        else:
            flash("发表成功, 请等待审核", "success")

        response = make_response()
        # response.mimetype = "text/html; charset=utf-8"
        response.location = url_for("main.post", post_id=post_id)
        response.status_code = 302
        if not current_user.is_authenticated:
            response.set_cookie("remember_author", form.author.data)
            response.set_cookie("remember_mail", form.mail.data)
            response.set_cookie("remember_url", form.url.data)
        return response


@main_bp.route("/comment/<int:comment_id>/reply", methods=["GET", "POST"])
def reply_comment(comment_id):

    comment = Comment.query.get_or_404(comment_id)

    return redirect(
        url_for(
            ".post",
            post_id=comment.post_id,
            comment_id=comment_id,
            author=comment.author,
        )
        + "#comment-form"
    )

app/templates/main/_posts.html
{% from 'bootstrap/pagination.html' import render_pagination %}
{% if posts %}
  <div class="articles pb-3"> 
    
    {% for post in posts %}
      <article class="widget widget-board">
        <header>
          <h4><a href="{{ url_for('main.post', post_id=post.id) }}">{{ post['title'] }}</a></h4>
        </header>
        <div class="content">
          <p>{{ post['content_html']|striptags|truncate }}</p>
        </div>
        <footer class="text-muted">
          <small>
            <a href="{{ url_for('main.category', category_id=post.category_id) }}">{{ post['category']['name'] }}</a>  &nbsp;&nbsp;|&nbsp;&nbsp;  阅读：{{ post['read_count'] }} &nbsp; 评论：<a href="{{ url_for('main.post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>
           <time class="float-right" datetime="{{ post['created'].strftime('%Y-%m-%d') }}">{{ moment(post.created).format('LL') }}</time>
           {{ post.created }}
          </small> 
        </footer>
      </article>
    {% endfor %}
  </div>

  {{ render_pagination(pagination,prev='上一页',next='下一页') }}
{% endif %}

app/templates/main/_sidebar.html
<aside class="col-md-3">
  <section class="my-3">
    <ul class="list-group">
      <li class="list-group-item"><b>搜索</b></li>  
      <li class="list-group-item">
        <form class="form-inline my-2 " action="/search">
        <input class="form-control bg-light " style="width:100%" type="search" name="keyword" placeholder="关键字" aria-label="Search" /> 
        <button class="btn btn-primary mt-3 mr-3">搜索</button> <a href="{{ url_for('main.random_post') }}" class="btn btn-outline-secondary mt-3">随便看看</a>
        </form>
      </li>
    </ul>
  </section>

  {% if options['sidebar_comment']|int %}
    {# if comments #} 
      <section class="my-3">
        <ul class="list-group" style="overflow-wrap: break-word;">
          <header class="list-group-item"><b>近期评论</b></header>
          {% for comment in comments %}
          <li class="list-group-item list-group-item-action"><h6>{{ comment['author'] }}：</h6><a href="{{ url_for('main.post', post_id=comment.post_id) }}#comment_id-{{ comment['id'] }}">{{ comment['content'] }}</a></li>
          {% endfor %}
        </ul>
      </section>
    {# endif #}
  {% endif %}

  {% if categories %} 
    <section class="my-3">
      <ul class="list-group">
        <header class="list-group-item"><b>分类目录</b></header>
        {% for category in categories %}
        <li class="list-group-item list-group-item-action"><a href="{{ url_for('main.category', category_id=category.id) }}">{{ category['name'] }}<span class="float-right badge badge-light">{{ category['posts']|length }}</span></a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}

  {% if tags %} 
    <section class="my-3">
      <ul class="list-group">
        <header class="list-group-item"><b>标签</b></header>
        <li class="list-group-item">
        
          {% for tag in tags %}
          <a class="btn btn-light btn-sm mb-1" href="{{ url_for('main.tag', tag_id=tag.id) }}">{{ tag['name'] }}</a>
        {% endfor %}
        </li>
      </ul>
    </section>
  {% endif %}

  {% if archives %} 
    <section class="my-3">
      <ul class="list-group">
        <header class="list-group-item"><b>文章归档</b></header>



        {# for archive in (archives[::-1]) #} {# 倒着遍历 #} 
        {% for archive in archives %}
        {# set archive_item = archive['year'] ~'-'~ archive['month'] #}

        <li class="list-group-item list-group-item-action"><a href="{{ url_for('main.archive', archive_year=archive['year'], archive_month=archive['month']) }}">{{ archive['year'] }}年{{ archive['month'] }}月<span class="float-right badge badge-light">{{ archive['count'] }}</span></a></li>
        {% endfor %}

      </ul>
    </section>
  {% endif %}

  {% if links %} 
    <section class="my-3">
      <ul class="list-group">
        <header class="list-group-item"><b>链接</b></header>
        {% for link in links %}
        <li class="list-group-item list-group-item-action"><a href="{{ link['url'] }}">{{ link['name'] }}</a></li>
        {% endfor %}
      </ul>
    </section>
  {% endif %}

</aside>

app/templates/main/about.html
{% extends 'base.html' %} 

{% block title %}关于{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-9">
            <section class="">
                <header class="p-3">
                    <h3>关于</h3> 
                </header>
                <div class="content bg-white border my-3 p-3">{{ options['blog_about']|safe }}</div>  
            </section>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock %} 

app/templates/main/archive.html
{% extends 'base.html' %} 

{% block title %}{{ archive.name }}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-9">
            
            <header class="p-3">
                <h4>{{ type }}：{{ archive.name }}</h4>
                <p class="text-muted mb-0">{{ archive.posts|length }} 篇文章</p>
            </header>
            {% include 'main/_posts.html' %}
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock %} 

app/templates/main/index.html
{% extends 'base.html' %} 
{% block title %}首页{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-9">
            {% include 'main/_posts.html' %}
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock %} 

app/templates/main/page.html
{% extends 'base.html' %} 

{% block title %}{{ page.title }}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-9">
            <section class="">
                <header class="p-3">
                    <h3>{{ page.title }}</h3> 
                </header>
                <div class="content p-3">{{ page.content|safe }}</div>  
            </section>
        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock %} 

app/templates/main/post.html
{% extends 'base.html' %} 
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block head %}
{{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='editormd/css/editormd.min.css') }}"/>
    <link href="https://cdn.bootcdn.net/ajax/libs/prism/1.22.0/themes/prism-okaidia.css" rel="stylesheet">
    <link href="https://cdn.bootcdn.net/ajax/libs/prism/1.22.0/plugins/line-numbers/prism-line-numbers.css" rel="stylesheet">
{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-md-9">
            <article id="article" class="widget widget-board">
            <header class="">
                <h3>{{ post.title }}</h3>
                <p class="text-muted">
                作者: <a href="{{ url_for('main.user', user_id=post.user_id) }}">{{post.user.name}}</a><br/>
                分类: <a href="{{ url_for('main.category', category_id=post.category_id) }}">{{ post.category.name }}</a><br/>
                阅读: {{ post.read_count }}<br/>
                时间: {# post.created.strftime('%Y-%m-%d %H:%m') #} {{ moment(post.created).format('LLL') }}
                </p>
                {% if post.tags %}
                    <p class="text-muted">
                        {% for tag in post.tags %}
                        <a class="btn btn-light btn-sm my-1" href="{{ url_for('.tag',tag_id=tag.id) }}">{{ tag.name }}</a>
                        {% endfor %}
                    </p>
                {% endif %}

                    {% if current_user.is_authenticated %}
                    <p>
                        <form class="inline" method="post" action="{{ url_for('admin.delete_post', post_id=post.id, next=url_for('.index')) }}">
                            <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_post',post_id=post.id) }}">编辑</a> 
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除吗?');">删除</button>
                        </form>
                    </p>
                    {% endif %}
            </header>
            <div class="content markdown-body" style="overflow-wrap: break-word;">{{ post['content_html']|safe }}</div>
            </article>
        {% if post_comments %}
            <section class="my-3 comment" id="comments">
                <ul class="list-group">
                    <header class="list-group-item">
                        <b>文章评论</b>
                    </header>

                    {% for comment in post_comments%}
                        <li class="list-group-item" id="comment_id-{{ comment.id }}">
                            <header>
                                <a {% if comment.url %} href="{{ comment.url }}" {% endif %}
            target="_blank"><b>{{comment.author}}:</b></a>
                                <span class="float-right">
                                    <small>{{ moment(comment.created).fromNow(refresh=True) }}</small>
                                </span>
                            </header>
                        
                            {% if comment.replied %}
                                <blockquote class="list-group-item bg-light mt-2 mb-2">{{ comment.replied.author }}:
                                    <br>{{ comment.replied.content }}
                                </blockquote>
                            {%- endif -%}
                        
                            <p class="content">
                                {{comment.content}}
                            </p>
                            <div># {{ loop.revindex }}
                                <span class="float-right">
                                    <form class="inline" method="post" action="{{ url_for('admin.delete_comment', comment_id=comment.id) }}">
                                    <a class="btn btn-light btn-sm"
       href="{{ url_for('.reply_comment', comment_id=comment.id) }}">回复</a>
                                    {% if current_user.is_authenticated %}
                                            <a class="btn btn-light btn-sm" href="mailto:{{ comment.mail }}">邮箱</a>
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                         <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除吗?');">删除</button>
                                         
                                        
                                    {% endif %}
                                    </form>
                                </span>
                            </div>
                        </li>
                    {%endfor%}
                    
                </ul>
            </section>

        {% endif %}

                {% if post_comments %}
                    {{ render_pagination(pagination, fragment='#comments') }}
                {% endif %}

            <section class="my-3" id="comment-form">
                <header class="py-3">
                    <h4>添加新评论</h4> 
                </header>
                {% if request.args.get('comment_id') %}
                <div class="alert alert-dark">
                回复 <strong>{{ request.args.get('author') }}</strong>:
                <a class="float-right" href="{{ url_for('.post', post_id=post.id) }}#comment_id-{{ request.args.get('comment_id') }}">取消</a>
                </div>
                {% endif %}

                {{ render_form(form, action=url_for('.comment_post', post_id=post.id, comment_id=request.args.get('comment_id'))) }}  
            </section>

            <section class="my-3" id="">
                <header class="py-3">
                    <h4>继续浏览</h4>
                </header>

                 {{ num }}

                    
                        {% if prev_post %}
                            <p>上一篇：</p>
                            <p><a href="{{ url_for('.post', post_id=prev_post.id) }}">{{ prev_post.title }}</a></p>
                        {% else %}
                            <p>上一篇：</p><p>没有了</p>
                        {% endif %}
                    

                   
                        {% if next_post %}
                            <p>下一篇：</p>
                            <p><a href="{{ url_for('.post', post_id=next_post.id) }}">{{ next_post.title }}</a></p>
                        {% else %}
                            <p>下一篇：</p><p>没有了</p>
                        {% endif %}
                    
                    
            
                  
            </section>

        </div>
        {% include 'main/_sidebar.html' %}
    </div>
{% endblock %} 

{% block scripts %}
{{ super() }}
    <script src="https://cdn.staticfile.org/prism/0.0.1/prism.min.js"></script>
    <script type="text/javascript">
        $('pre').addClass("line-numbers");
    </script>
{% endblock %}