app/blueprints/admin.py
from flask import (
    current_app,
    flash,
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    abort,
    make_response,
)
from ..models import Option, Page, User, Category, Tag, Post, Comment, Link
from ..extensions import db
from ..forms import (
    LoginForm,
    PostForm,
    PageForm,
    CategoryForm,
    TagForm,
    CommentForm,
    OptionForm,
    LinkForm,
    SearchForm,
)

from flask_login import login_required, current_user

from ..utils import redirect_back

admin_bp = Blueprint("admin", __name__)


@admin_bp.before_request
@login_required
def login_protect():
    pass


@admin_bp.route("/option", methods=["GET", "POST"])
def option():
    form = OptionForm()
    blog_title = Option.query.filter_by(name="blog_title").first()
    blog_sub_title = Option.query.filter_by(name="blog_sub_title").first()
    blog_navbar = Option.query.filter_by(name="blog_navbar").first()
    blog_footer = Option.query.filter_by(name="blog_footer").first()
    sidebar_comment = Option.query.filter_by(name="sidebar_comment").first()
    comment_review = Option.query.filter_by(name="comment_review").first()

    if form.validate_on_submit():
        blog_title.value = form.blog_title.data
        blog_sub_title.value = form.blog_sub_title.data
        blog_navbar.value = form.blog_navbar.data
        blog_footer.value = form.blog_footer.data
        sidebar_comment.value = form.sidebar_comment.data
        comment_review.value = form.comment_review.data

        db.session.commit()
        flash("设置保存成功", "success")
        return redirect(url_for("main.index"))
    form.blog_title.data = blog_title.value
    form.blog_sub_title.data = blog_sub_title.value
    form.blog_navbar.data = blog_navbar.value
    form.blog_footer.data = blog_footer.value
    form.sidebar_comment.data = int(sidebar_comment.value)
    form.comment_review.data = int(comment_review.value)

    return render_template("admin/option.html", form=form)


@admin_bp.route("/manage_pages")
def manage_pages():
    pages = Page.query.all()
    return render_template("admin/manage_pages.html", pages=pages)


@admin_bp.route("/edit_page/<int:page_id>", methods=["GET", "POST"])
def edit_page(page_id):
    page = Page.query.get_or_404(page_id)
    form = PageForm()
    if form.validate_on_submit():
        page.title = form.title.data
        page.slug = form.slug.data
        page.content = form.content.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_pages"))
    form.title.data = page.title
    form.slug.data = page.slug
    form.content.data = page.content
    return render_template("admin/page.html", form=form, type="编辑")


@admin_bp.route("/add_page", methods=["GET", "POST"])
def add_page():
    form = PageForm()
    if form.validate_on_submit():
        page = Page(
            title=form.title.data, slug=form.slug.data, content=form.content.data
        )
        db.session.add(page)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_pages"))
    return render_template("admin/page.html", form=form, type="添加")


@admin_bp.route("/page/<int:page_id>/delete", methods=["POST"])
def delete_page(page_id):
    page = Page.query.get_or_404(page_id)
    db.session.delete(page)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_categories")
def manage_categories():
    categories = Category.query.all()
    return render_template("admin/manage_categories.html", categories=categories)


@admin_bp.route("/edit_category/<int:category_id>", methods=["GET", "POST"])
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_categories"))
    form.name.data = category.name
    return render_template("admin/category.html", form=form, type="编辑")


@admin_bp.route("/add_category", methods=["GET", "POST"])
def add_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_categories"))
    return render_template("admin/category.html", form=form, type="添加")


@admin_bp.route("/category/<int:category_id>/delete", methods=["POST"])
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_tags")
def manage_tags():
    tags = Tag.query.all()
    return render_template("admin/manage_tags.html", tags=tags)


@admin_bp.route("/edit_tag/<int:tag_id>", methods=["GET", "POST"])
def edit_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    form = TagForm()
    if form.validate_on_submit():
        tag.name = form.name.data
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("admin.manage_tags"))
    form.name.data = tag.name
    return render_template("admin/tag.html", form=form, type="编辑")


@admin_bp.route("/add_tag", methods=["GET", "POST"])
def add_tag():
    form = TagForm()
    if form.validate_on_submit():
        tag = Tag(name=form.name.data)
        db.session.add(tag)
        db.session.commit()
        flash("添加成功", "success")
        return redirect(url_for("admin.manage_tags"))
    return render_template("admin/tag.html", form=form, type="添加")


@admin_bp.route("/tag/<int:tag_id>/delete", methods=["POST"])
def delete_tag(tag_id):
    tag = Tag.query.get_or_404(tag_id)
    db.session.delete(tag)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_posts")
def manage_posts():
    page = request.args.get("page", 1, type=int)
    pagination = Post.query.order_by(Post.created.desc()).paginate(page, per_page=10)

    return render_template(
        "admin/manage_posts.html",
        page=page,
        pagination=pagination,
        posts=pagination.items,
    )


@admin_bp.route("/write_post", methods=["GET", "POST"])
def write_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        content_html = request.form["fancy-editormd-html-code"]
        category = Category.query.get(form.category.data)
        tags = []
        for tag_id in form.tags.data:
            tag = Tag.query.get_or_404(tag_id)
            tags.append(tag)

        post = Post(
            title=title,
            content=content,
            content_html=content_html,
            category=category,
            tags=tags,
        )

        db.session.add(post)
        db.session.commit()
        flash("文章已发布", "success")
        return redirect(url_for("main.post", post_id=post.id))
    return render_template("admin/post.html", form=form, type="写")


@admin_bp.route("/edit_post/<int:post_id>", methods=["GET", "POST"])
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.content_html = request.form["fancy-editormd-html-code"]
        post.category_id = form.category.data
        tags = []
        for tag_id in form.tags.data:
            tag = Tag.query.get_or_404(tag_id)
            tags.append(tag)
        post.tags = tags
        db.session.commit()
        flash("编辑成功", "success")
        return redirect(url_for("main.post", post_id=post_id))
    form.title.data = post.title
    form.category.data = post.category

    tag_id_list = []
    for tag in post.tags:
        tag_id_list.append(tag.id)
    form.tags.data = tag_id_list

    form.content.data = post.content

    return render_template("admin/post.html", form=form, type="编辑")


@admin_bp.route("/post/<int:post_id>/delete", methods=["POST"])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_comments")
def manage_comments():
    page = request.args.get("page", 1, type=int)

    if request.args.get("filter") == "review":
        pagination = (
            Comment.query.filter_by(reviewed=False)
            .order_by(Comment.created.desc())
            .paginate(page, per_page=10)
        )
    elif request.args.get("filter") == "admin":
        pagination = (
            Comment.query.filter_by(author="admin")
            .order_by(Comment.created.desc())
            .paginate(page, per_page=10)
        )
    else:
        pagination = Comment.query.order_by(Comment.created.desc()).paginate(
            page, per_page=10
        )

    return render_template(
        "admin/manage_comments.html",
        page=page,
        pagination=pagination,
        comments=pagination.items,
        total_count=Comment.query.count(),
        review_count=Comment.query.filter_by(reviewed=False).count(),
    )


@admin_bp.route("/comment/<int:comment_id>/approve", methods=["POST"])
def approve_comment(comment_id):
    # 切换审核状态
    comment = Comment.query.get_or_404(comment_id)

    if comment.reviewed:
        comment.reviewed = False
    else:
        comment.reviewed = True

    db.session.commit()
    flash("操作成功", "success")
    return redirect_back()


@admin_bp.route("/comment/<int:comment_id>/delete", methods=["POST"])
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash("删除成功", "success")
    return redirect_back()


@admin_bp.route("/manage_links")
def manage_links():

app/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from ..models import Option, Page, User, Category, Tag, Post, Comment, Link
from ..forms import LoginForm, PostForm, PageForm, CategoryForm, TagForm, CommentForm, OptionForm, SearchForm

from flask_login import login_user, logout_user, login_required, current_user
from ..utils import redirect_back

auth_bp = Blueprint("auth", __name__)


@auth_bp.route("/login", methods=["GET", "POST"])
def login():

    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    form = LoginForm()
    if form.validate_on_submit():
        name = form.name.data
        password = form.password.data
        remember = form.remember.data
        user = User.query.first()
        if user:
            if name == user.name and user.validate_password(password):
                login_user(user, remember)
                flash("欢迎回来", "info")
                return redirect_back()
            flash("用户名或密码无效", "warning")
        else:
            flash("用户名不存在", "warning")

    return render_template("auth/login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("注销成功", "info")
    return redirect_back()

app/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}

<!DOCTYPE html>
<html lang="zh-Hans" class="h-100">
  <head>
    {% block head %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="description" content="" />
      <meta name="keywords" content="" />
      <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.5.3/css/bootstrap.min.css">
      <!--<link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">-->
      <style>
        body {
          background-color:#f2f2f7; 
          font-family: -apple-system, BlinkMacSystemFont, "Helvetica Neue", Helvetica, sans-serif;
        }

        .widget {
          margin-top: 1rem!important;
          margin-bottom: 1rem!important;
          border: 1px solid #dee2e6!important;
          border-radius: .25rem;
          background-color: #fff!important;
        }

        .widget-board {
          padding: 1rem!important;
        }



      </style>
      <title>{% block title %}{% endblock %} - {{ options['blog_title'] }}</title>
    {% endblock head %}
  </head>

  <body class="d-flex flex-column h-100" style="padding-top: 5rem"> 
    <nav class="navbar bg-white navbar-light navbar-expand-md fixed-top border-bottom ">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}"><b>{{ options['blog_title'] }}</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {{ render_nav_item('main.index','首页') }}
                {% for page in pages %}
                {{ render_nav_item('main.page', page.title, slug=page.slug) }}
                  
                {% endfor %}
 
          </ul>

          <ul class="navbar-nav ml-auto">   
            {# options['blog_navbar']|safe #}


<!--
                  <form class="form-inline my-2" action="/search">
                  <input class="form-control bg-light " style="width:100%" type="search" name="keyword" placeholder="关键字" aria-label="Search" /> 
                  <button class="btn btn-primary mt-3 mr-3 inline">搜索</button>
                  </form>
                -->

            {% if current_user.is_authenticated %}      
              {{ render_nav_item('admin.write_post','写文章',use_li=True) }}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown"  role="button" data-toggle="dropdown" aria-haspopup="true"  aria-expanded="false"> 管理 </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">

                    <a class="dropdown-item" href="{{ url_for('admin.option') }}">设置</a>

                    <a class="dropdown-item" href="{{ url_for('admin.manage_pages') }}">页面</a>

                    <a class="dropdown-item" href="{{ url_for('admin.manage_categories') }}">分类</a>

                    <a class="dropdown-item" href="{{ url_for('admin.manage_tags') }}">标签</a>

                    <a class="dropdown-item" href="{{ url_for('admin.manage_posts') }}">文章</a>

                    <a class="dropdown-item" style="" href="{{ url_for('admin.manage_comments') }}">评论{% if review_comments_count %}<span style="" class="float-right badge badge-light pt-2">{{ review_comments_count }}</span>{% endif %}</a>

                    <a class="dropdown-item" href="{{ url_for('admin.manage_links') }}">链接</a>     
                </div>
              </li>
              <li class="nav-item nav-link"><a href="{{ url_for('auth.logout')}}  ">注销</a></li>
            {% else %}
              <li class="nav-item nav-link"><a href="{{ url_for('auth.login') }} ">登录</a></li>
            {% endif %}
         
        </ul>

        </div>
      </div>
    </nav>

    <header>
      <div class="container">
        {% for message in get_flashed_messages(with_categories=True) %}
          <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
          </div>
        {% endfor %}
      </div>
    </header>

    <main class="container">
      {% block header %}{% endblock %}
      {% block main %}{% endblock %}
    </main>

    <footer class="container-full mt-auto bg-light border-top">
      {% block footer %}
      <div class="py-5 text-muted text-center"> 
          <p><small>© 2015-2023 空心. All Rights Reserved.<br/>
            Powered by <a target="_blank" href="https://github.com/zero-ljz/onelog">Onelog</a>.
          </small></p>
          {{ options['blog_footer']|safe }}
      </div>
      {% endblock %}
    </footer>
   
    {% block scripts %}
      <script src="https://cdn.staticfile.org/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://cdn.staticfile.org/twitter-bootstrap/4.5.3/js/bootstrap.bundle.min.js"></script>
      {# moment.include_moment() #}
      {# moment.locale(auto_detect=True) #}
      <script src="https://cdn.bootcdn.net/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"></script>
      <script>
        moment.locale("en");
        function flask_moment_render(elem) {
            timestamp = moment($(elem).data('timestamp'));
            func = $(elem).data('function');
            format = $(elem).data('format');
            timestamp2 = $(elem).data('timestamp2');
            no_suffix = $(elem).data('nosuffix');
            args = [];
            if (format)
                args.push(format);
            if (timestamp2)
                args.push(moment(timestamp2));
            if (no_suffix)
                args.push(no_suffix);
            $(elem).text(timestamp[func].apply(timestamp, args));
            $(elem).removeClass('flask-moment').show();
        }
        function flask_moment_render_all() {
            $('.flask-moment').each(function() {
                flask_moment_render(this);
                if ($(this).data('refresh')) {
                    (function(elem, interval) { setInterval(function() { flask_moment_render(elem) }, interval); })(this, $(this).data('refresh'));
                }
            })
        }
        $(document).ready(function() {
            flask_moment_render_all();
        });
        </script>
              <script>
        var locale = window.navigator.userLanguage || window.navigator.language;
        moment.locale(locale);
        </script>
              
    {% endblock %}
  </body>
</html>

app/templates/macro.html
{% macro showc(content) %}
666
{{content}}

{% endmacro %}